### ISSUE TITLE
An error occurred when running demo/track.py

### ISSUE THREAD

**Issue by jihg88** [statho/ScoreHMR#7]
Hi,thans for your great work!I just want to test it on the video,but when running with the track.py on line 134 :Error in forward_face_index_map_1: no kernel image is available for execution on the device
```
        rend_depth = self.neural_renderer(
            pred_verts,
            face_tensor[None].expand(pred_verts.shape[0], -1, -1).int(),
            # textures=texture_atlas_rgb,
            mode="depth",
            K=K,
            R=R,
            t=t,
        )
```

Logs:
[2024-03-20 11:15:01,774][pytorch_lightning.utilities.migration.utils][INFO] - Lightning automatically upgraded your loaded checkpoint from v1.8.1 to v2.2.1. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../../../../home/lyx/.cache/4DHumans/logs/train/multiruns/hmr2/0/checkpoints/epoch=35-step=1000000.ckpt`
[2024-03-20 11:15:01,780][torch.distributed.nn.jit.instantiator][INFO] - Created a temporary directory at /tmp/tmp0fqy2lvo
[2024-03-20 11:15:01,780][torch.distributed.nn.jit.instantiator][INFO] - Writing /tmp/tmp0fqy2lvo/_remote_module_non_scriptable.py
WARNING: You are using a SMPL model, with only 10 shape coefficients.
[2024-03-20 11:15:04,210][phalp.trackers.PHALP][INFO] - Loading Predictor model...
[2024-03-20 11:15:04,389][phalp.trackers.PHALP][INFO] - Loading Detection model...
[2024-03-20 11:15:08,291][detectron2.checkpoint.detection_checkpoint][INFO] - [DetectionCheckpointer] Loading from https://dl.fbaipublicfiles.com/detectron2/ViTDet/COCO/cascade_mask_rcnn_vitdet_h/f328730692/model_final_f05665.pkl ...
[2024-03-20 11:15:10,244][detectron2.checkpoint.detection_checkpoint][INFO] - [DetectionCheckpointer] Loading from https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_3x/139653917/model_final_2d9806.pkl ...
[2024-03-20 11:15:10,357][phalp.trackers.PHALP][INFO] - Setting up Visualizer...
[2024-03-20 11:15:10,704][phalp.trackers.PHALP][INFO] - Setting up DeepSort...
[2024-03-20 11:15:10,705][phalp.trackers.PHALP][INFO] - Saving tracks at : demo_out/videos/phalp_out/breakdancing/results/breakdancing
[2024-03-20 11:15:14,537][pyscenedetect][INFO] - Downscale factor set to 7, effective resolution: 274 x 154
[2024-03-20 11:15:14,538][pyscenedetect][INFO] - Detecting scenes...
[2024-03-20 11:15:14,841][phalp.trackers.PHALP][INFO] - Detected shot change at frame: 
Tracking : breakdancing 🚶  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% eta : -:--:--  time elapsed : 0:00:02Error in forward_face_index_map_1: no kernel image is available for execution on the device

my cuda version=11.7,so i installed pytorch with : `conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia`,i don't know how to fix the problem.

**Comment by statho** [comment]
It seems that the neural renderer package is not properly installed.

You can use the PHALP_Prime_HMR2 tracker by removing the comment in this [line](https://github.com/statho/ScoreHMR/blob/master/demo/track.py#L263) instead of the default one.

**Comment by jihg88** [comment]
Thank you for your reply,it works now！
